version: "3.2"
services:
  oracle193db:
    container_name: oracle193db
    image: banglamon/oracle193db:19.3.0-ee
    environment:
      ORACLE_SID: "orcl"
      ORACLE_PDB: "orclpdb"
      ORACLE_PWD: "Oracle123"
    ports:
      - "1521:1521"
      - "8081:8081"
    volumes:
      # - D:/Docker/oracle19c/data:/opt/oracle/oradata
      - oracle_data:/opt/oracle/oradata
volumes:
  oracle_data:
    external: true
