version: "3.2"
services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "ChangeMeNow!0"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      #- D:/Docker/ms-sql/data:/var/opt/mssql
      - ms_sql_data:/var/opt/mssql
volumes:
  ms_sql_data:
    external: true
